name: shell commands
on: 
  - push
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "hello"
      - name: multi line string
        run: | #=enables multiple commands
          pwd
          node -v
          ls -a
      - name: python command
        run: |
          import platform  #import platform as a package
          print(platform.processor())  #to find out processor type
        shell: python
  run-windows-commands:
    runs-on: windows-latest  
    needs: ["run-shell-commands"]  # has to run before windows
    steps:
      - name: Directory
        run: pwd
        shell: bash
     